services:
  - name: falcon-api
    type: web
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
